### ISSUE TITLE
Have a problem in mxnet WarpCTC

### ISSUE THREAD

**Issue by Wangweilai1** [oyxhust/CNN-LSTM-CTC-text-recognition#12]
When I run this program in lstm.py file have a error, How can i deal with. Thanks
sm = mx.sym.WarpCTC(data=pred, label=label, label_length = num_label, input_length = seq_len)

D:\DeepLearning_Demo\CNN_LSTM_CTC\CNN-LSTM-CTC-text-recognition-master>python train_lstm.py
Traceback (most recent call last):
  File "train_lstm.py", line 196, in <module>
    symbol = sym_gen(SEQ_LENGTH)
  File "train_lstm.py", line 187, in sym_gen
    num_label = num_label)
  File "D:\DeepLearning_Demo\CNN_LSTM_CTC\CNN-LSTM-CTC-text-recognition-master\symbol\lstm.py", line 79, in lstm_unroll
    sm = mx.sym.WarpCTC(data=pred, label=label, label_length = num_label, input_length = seq_len)
**AttributeError: module 'mxnet.symbol' has no attribute 'WarpCTC'**

**Comment by oyxhust** [comment]
You should install the warpctc first. Please check this issue: https://github.com/oyxhust/CNN-LSTM-CTC-text-recognition/issues/4.

**Comment by sivaaninraj** [comment]
how did you resolve this ?
