### ISSUE TITLE
 ImportError: No module named mxnet

### ISSUE THREAD

**Issue by qianfeihong** [oyxhust/CNN-LSTM-CTC-text-recognition#16]
I have used your version of mxnet and warpctc downloaded from your BaiduYun. I built mxnet and warpctc successfully. Also, I enabled warpctc in mxnet. However, when I run the train_lstm.py, the problem went that "import mxnet as mx" ImportError: No module named mxnet. Then I realized that i should add mxnet path in the environment. I add "export PYTHONPATH=~/mxnet/python" at the end of  .bashrc. When I echo $PATH in the command line, the result shows that /home/qian/mxnet/python is successfully added. However, when i run the train_lstm.py again, the  problem still existed. How can I solve this problem? Thank you!

**Comment by qianfeihong** [comment]
import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "mxnet/base.py", line 34, in _load_lib
    lib_path = libinfo.find_lib_path()
  File "mxnet/libinfo.py", line 36, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the files.

how can i solve this??
